### ISSUE TITLE
Travis Test Breakage

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk-client-js#100]
Travis is currently failing for this repo due to a trigger test failure.

Test output:

```
  ✖ triggers › fire a trigger   
  t.true(update_result.hasOwnProperty('activationId'))
                       |                              
                       false                          
```

```
  1. triggers › fire a trigger
  AssertionError: false === true
    triggers.test.js:112:7
    process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by csantanapr** [comment]
Ah is this because the fire trigger API changed in the backend?

I guess the test can be fixed by adding a rule and dummy action echo so the fire response back with 202 and activation id

**Comment by jthomas** [comment]
@csantanapr is correct. Fixed.
