### ISSUE TITLE
add support for retries

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk-client-js#119]
in some scenarios, the connection to openwhisk may be unreliable. for example, certain versions of nodejs on linux yield routine ETIMEDOUT or ESOCKETTIMEOUT or ECONNRESET (especially the last one); all of these errors are transient, and can be addressed via retry.

i propose that we can support retries with only a few lines of code change, e.g. by wrapping the `rp` call in client.request with a `promise-retry`. PR pending

**Comment by jthomas** [comment]
Implementing retry logic for connection errors is not normally the responsibility of the client library. This is not standard behaviour for client libraries. Responsibility for failure recovery errors should be handled by the client application.

**Comment by starpit** [comment]
possibly, but every single user of this npm will face the issue, when talking on linux to ibm cloud.
