### ISSUE TITLE
namespace.list doesn't pass on user-agent header

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk-client-js#135]
a simple fix of passing through the `options`

**Comment by jthomas** [comment]
:+1: PR?

**Comment by starpit** [comment]
yup, some time today i hope. also certain activation operations have the same issue.

i'm also thinking of adding a way to disable user-agent headers entirely. some servers (namely openwhisk itself :( ) do not support user-agent headers in their CORS config
