### ISSUE TITLE
Error.captureStackTrace is not supported by firefox

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk-client-js#137]
https://github.com/apache/incubator-openwhisk-client-js/blob/master/lib/openwhisk_error.js#L7

this line assumes that `Error.captureStackTrace` is defined. it is not on Firefox, and perhaps in other browsers. i suggest that we at least protect against it being undefined.

**Comment by jthomas** [comment]
Interesting, I hadn't even thought about using the library from a browser, does it work? PR LGTM.

**Comment by starpit** [comment]
yes indeed. the only limitation i see at this point is here:

https://github.com/apache/incubator-openwhisk/pull/4010

**Comment by jthomas** [comment]
This is now fixed. 
https://github.com/apache/incubator-openwhisk-client-js/blob/master/lib/openwhisk_error.js#L21-L24
