### ISSUE TITLE
Updating package parameters doesn't seem to take affect

### ISSUE THREAD

**Issue by macdonst** [apache/incubator-openwhisk-client-js#143]
I'm attempting to update my package parameters while executing an action. Unfortunately, no matter what I try the parameters don't seem to be updated. 

Here is some sample action code that illustrates the problem:

```
const openwhisk = require('openwhisk');

function extractPackageName(action) {
  return action.split('/')[2];
}

function main(params) {
  const ow = openwhisk();
  const packageName = extractPackageName(process.env['__OW_ACTION_NAME']);
    
  return ow.packages
    .get(packageName)
    .then(pack => {
        // a and b not in package
        console.log(pack);
        pack.parameters.push({key: 'a', value: 'a'});
        pack.parameters.push({key: 'b', value: 'b'});
        // alternatively tried
        // pack.parameters.a = 'a';
        // pack.parameters.b = 'b';
        // a and b included in the package
        console.log(pack);
        return ow.packages
          .update(pack)
          .then(updatedPackage => {
            // a and b not in package
            console.log(updatedPackage);
            return {
              ...params
            };
          })
          .catch(err => {
            return err;
          });
    })
    .catch(function(err) {
      return err;
    });
}
```

As well subsequent calls to this action do not show the updated `a` and `b` parameters I've attempted to add.

**Comment by macdonst** [comment]
@starpit Yeah, I updated the code above as that was a copy and paste from my trashing trying to figure out what I was doing wrong. I have the same issue if I push new object into the parameters array. 

As well, if I run the example code directly from here: https://github.com/apache/incubator-openwhisk-client-js#update-package-parameters I still get the same issue.

**Comment by starpit** [comment]
you have tried `ow.packages.update({ name, package})`? your example has `ow.packages.update(pack)` which i think won't work.

**Comment by macdonst** [comment]
@starpit here is a smaller example that still doesn't work that is based off the sample code from the README.

```
const openwhisk = require('openwhisk');

function extractPackageName(action) {
  return action.split('/')[2];
}

function main(params) {
  const ow = openwhisk();
  const packageName = extractPackageName(process.env['__OW_ACTION_NAME']);
    
const package1 = {
  parameters: [
    {key: "colour", value: "green"},
    {key: "name", value: "Freya"}
  ]
}

return ow.packages.update({packageName, package1}).then(newPackage => {
  console.log('updated package:');
  console.log(newPackage);
  return { ...params };
}).catch(err => {
  console.error('failed to update package', err);
  return err;
});
}

exports.main = main;
```

**Comment by macdonst** [comment]
Yeah, using `ow.packages.update({ name, package})` has resolved the issue but I'm not sure why that would be different than `ow.packages.update(pack)` where pack is an object that has a name and parameters properties.

**Comment by starpit** [comment]
yes, i agree that this API could be refined; it is not a reflexive API.

**Comment by macdonst** [comment]
Okay, well I'm going to close this a user error :)
