### ISSUE TITLE
`packages/refresh` is missing

### ISSUE THREAD

**Issue by shazron** [apache/incubator-openwhisk-client-js#144]
Exists in the go client:
https://github.com/apache/incubator-openwhisk-client-go/commit/0da9b27e45c97d68eaa976a21dc581aa449765da#diff-c1680fb631152dc4662ea9b2b980680b

**Comment by rabbah** [comment]
it should actually be removed from the go client - it's a left over bit from pre-apache days and has no effect in openwhisk.

**Comment by rabbah** [comment]
See https://github.com/apache/incubator-openwhisk-cli/issues/119

**Comment by shazron** [comment]
Thanks for the clarification!

**Comment by shazron** [comment]
@rabbah since I have your attention, what about `wsk package bind`, is that still relevant?

**Comment by rabbah** [comment]
That is a valid command for creating a package binding.
