### ISSUE TITLE
How to set http proxy in openwhisk sdk through nodejs js client 

### ISSUE THREAD

**Issue by karanrk** [apache/incubator-openwhisk-client-js#145]
I am trying to set http proxy agent from nodejs client but i don't see any relevant config api that would help me to set the proxy agent.

I was looking for something like this
 openwhisk.config.httpOptions.agent= new HttpsProxyAgent(url.parse(proxy));

but the above one fails since there is no httpOption in openwhisk.

**Comment by jthomas** [comment]
This client library uses the [Needle HTTP client](https://github.com/tomas/needle) to interact with the OpenWhisk platform API. Looking at the HTTP client, it does seem to [support a HTTP proxy parameter](https://github.com/tomas/needle#request-options) but this option has not been implemented in the SDK. 

If you want to have a go at submitting a PR to implement this option as a pass-thru to the library, it would be great.

**Comment by karanrk** [comment]
@jthomas  I fixed it, will be submitting a PR soon!
