### ISSUE TITLE
Support adding your own cert and key (like the Go cli)

### ISSUE THREAD

**Issue by shazron** [apache/incubator-openwhisk-client-js#149]
I would like to add this support in a PR.

These options will be passed into the `client.js` constructor: https://github.com/apache/incubator-openwhisk-client-js/blob/c2de73b69db3c95fa874c009c5b9b92302eecbd8/lib/client.js#L84

... and these options will be set in the underlying `needle` module that will use them as `cert` and `key` options.

Any concerns?

**Comment by jthomas** [comment]
sounds fine - open the PR?

**Comment by shazron** [comment]
Thanks! See #152
