### ISSUE TITLE
Support setting the apiversion (like the Go cli)

### ISSUE THREAD

**Issue by shazron** [apache/incubator-openwhisk-client-js#150]
I would like to add this support in a PR.

These options will be passed into the `client.js` constructor: https://github.com/apache/incubator-openwhisk-client-js/blob/c2de73b69db3c95fa874c009c5b9b92302eecbd8/lib/client.js#L84

... and this option will be passed to this function:
https://github.com/apache/incubator-openwhisk-client-js/blob/313fcec68f7393f245fd3bacf4fa512c56028bef/lib/client.js#L107

Any concerns?

**Comment by jthomas** [comment]
sounds fine - open the PR?

**Comment by shazron** [comment]
Thanks! see #151
