### ISSUE TITLE
3.19.0 tag is missing in the repo

### ISSUE THREAD

**Issue by shazron** [apache/incubator-openwhisk-client-js#164]
npm has the 3.19.0 version as published, but no tag exists in this repo. https://www.npmjs.com/package/openwhisk

Expected:
3.19.0 tag exists

Actual:
3.19.0 tag does not exist

**Comment by shazron** [comment]
@jthomas FYI before you cut the new release. Probably steps 13 and on were accidentally skipped: https://github.com/apache/incubator-openwhisk-release/blob/master/docs/release_instructions.md

**Comment by dgrove-oss** [comment]
I added the 3.19.0 tag to the commit that matches the approved release per the voting thread.
