### ISSUE TITLE
Support passing annotations for rules

### ISSUE THREAD

**Issue by shazron** [apache/incubator-openwhisk-client-js#165]
Related: https://github.com/apache/incubator-openwhisk-cli/issues/426

I inspected the `rules` code and there doesn't seem to be any code that will pass on annotations. 

Looks like `ruleBody`:
https://github.com/apache/incubator-openwhisk-client-js/blob/e772a2fd0811f4a2c7a0cc4e832c4d08e192b320/lib/rules.js#L35
should accept annotations in the options like `actions.js`:
https://github.com/apache/incubator-openwhisk-client-js/blob/e772a2fd0811f4a2c7a0cc4e832c4d08e192b320/lib/actions.js#L76

**Comment by erezh16** [comment]
It seems this issue is focused on the JS client (unlike #426). 
1. Can you please fix the title to reflect that?
2. I guess this warrants a broader review of this aspect (supporting annotations for rules) in additional client libraries - Python, Go, etc.

**Comment by shazron** [comment]
1. The issue is filed in the incubator-openwhisk-client-js repo, so I'm not sure why we need to distinguish further. Seems redundant to me?
2. This feature is actually needed since `wskdeploy` does support annotations for rules. See https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/specification/html/spec_shared_entity_schema.md#shared-entity-schema

**Comment by jthomas** [comment]
@shazron You are right - it looks like the JS SDK has missed this feature. Would you like to open a PR?
