### ISSUE TITLE
CI with travis

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-client-js#3]
Setup a Travis build to periodically run integration test against an openwhisk deployment (or the publicly hosted service).

**Comment by jthomas** [comment]
I've now added the basic Travis CI YML to set up running the unit tests for this project. 
Talking to @rabbah about getting this module into the NodeJS Action environment, we want to have integration testing set up. 

> If we install the package in the docker file and replace the tests that do invoke/fire with your library for at least those two it would give us parity with the whisk object.

The project does have integration tests already but I'm not sure what the best way to test these against a live OW platform instance from Travis is. 

cc @csantanapr & @bjustin-ibm

**Comment by rabbah** [comment]
This pull request will add the package to the base images: https://github.com/openwhisk/openwhisk/pull/1539. We need to resolve #1 and as a bonus #14 as well.

**Comment by jthomas** [comment]
I've now resolved #1 and #14 with 2.3.0.
What's the next step for this issue?

**Comment by jthomas** [comment]
@csantanapr & @rabbah given some of the recent issues, I'd like to get the Travis CI set up running the integration tests to catch library bugs and platform API changes. 

Do we have an integration environment I can point to?

**Comment by csantanapr** [comment]
What you mean an integration environment to point. 

You need to git clone OpenWhisk from git repo and build and deploy during Travis locally and the run your tests against local OpenWhisk running on Travis

We have several repos that do this already, I did one recently for apigateway and got the build down to 14 minutes to build and deploy OpenWhisk only with nodejs runtime installed.

**Comment by csantanapr** [comment]
See the following Travis configuration file
https://github.com/openwhisk/openwhisk-apigateway/blob/master/.travis.yml

The setup and build scripts are the ones related to OpenWhisk

So the direction will be to run 
Setup to git clone OpenWhisk 
Build to build and deploy OpenWhisk with gradle and ansible
Then configure env and CLI to point to local OpenWhisk apihost using guest namespace
Then run npm tests

**Comment by jthomas** [comment]
Thanks for explaining, I didn't think of that approach. 
I'll see if I can set this up.

**Comment by csantanapr** [comment]
I can help

**Comment by bjustin-ibm** [comment]
Resolved by #59
