### ISSUE TITLE
TypeScript Typings

### ISSUE THREAD

**Issue by jlost** [apache/incubator-openwhisk-client-js#35]
TypeScript definitions at @types/openwhisk would be helpful.

**Comment by jthomas** [comment]
I'm not familiar with TypeScript, can you explain what this would be and why it is useful?

**Comment by rabbah** [comment]
types FTW!

**Comment by jlost** [comment]
TypeScript helps you defined _explicit_ contracts for your JavaScript and mark up your code with type definitions. Strong type checking in your code prevents many common errors, enforces explicit interfaces (self-documenting code), and enables intellisense / code completion.  

Since Angular 2 embraced TypeScript, it has really gone mainstream and is commonly used with NodeJS. TypeScript definitions are available for most major JavaScript libraries -- there are nearly 3,000 definitions available in the DefinitelyTyped repository, and that isn't counting the libraries that include types because they're natively implemented in TypeScript.

So the benefits for users are -- explicit interfaces, error prevention, and code completion. Benefits to the project are better adoption rates, more positive community perception, and explicit documentation of all method & class interfaces.

**Comment by jthomas** [comment]
Thanks for explaining - that sounds like a good idea. 

If you would like to work on this, I'd be happy to accept this into the project.

**Comment by ert78gb** [comment]
I could help, but I think better if the code convert to typescript. Every js file is typescript file

**Comment by jlost** [comment]
I ended up making some typings as I went, but nothing accurate enough to publish... Maybe I'll throw them here anyway in case others want to chip in.

**Comment by jthomas** [comment]
Having TypeScript typings is something that would be useful for the project. Converting the entire project to TypeScript is not a priority for the project at the moment. 

@jlost I'd be interested to see the resources you have, how did you create them?

**Comment by jlost** [comment]
Example: 

```
declare module OpenWhisk {
    export interface OpenWhiskActivation<T> {
        activationId: string;
        annotations: any[];
        duration: number;
        end: number;
        logs: any[];
        name: string;
        namespace: string;
        publish: boolean;
        response: OpenWhiskResponse<T>;
        start: number;
        subject: string;
        version: string;
    }

    export interface OpenWhiskResponse<T> {
        result: T;
        status: string; //"success" / ??? 
        success: boolean;
    }
}
```

I created this by hand by looking at actual OpenWhisk activations. 

A good halfway point for this project would be JSDoc, which would formalize the interfaces enough to make TS definitions easy to create and also power code completion within editors. That way you don't have to learn or implement any extra tools.
