### ISSUE TITLE
[Error][minikube] ENOTFOUND nginx.openwhisk nginx.openwhisk:443

### ISSUE THREAD

**Issue by jakub-gawlas** [apache/incubator-openwhisk-client-js#56]
Hi folks! 

I deploy OpenWhisk locally on minikube and it's my action:
```js
const openwhisk = require('openwhisk');

function main(params){
  return new Promise((resolve, reject) => {
    ow.actions.list().then(resolve);
  });
}
```
Result of invoke it is error:
```bash
Unhandled rejection Error: Error encountered calling OpenWhisk: Error: getaddrinfo ENOTFOUND nginx.openwhisk nginx.openwhisk:443
```

Maybe someone experienced similar issue and can help?

Cheers 🥂

**Comment by jthomas** [comment]
Hello @jakub-gawlas, can you give me a link to the instructions you followed for running OW on Minikube? I'll spin it up locally and try it out.

**Comment by rabbah** [comment]
This sounds like a dns issue with kubernetes. If you can't resolve nginx.openwhisk from inside an action container you can't reach the edge gateway. 

@DanLavine or @bbrowning may be able to help.

**Comment by csantanapr** [comment]
Open issue in kube repo asking how an action can address the controller or nginx from inside.
https://github.com/apache/incubator-openwhisk-deploy-kube/issues

Nothing we can do in this client-js to fix this.
