### ISSUE TITLE
support optional leading slash in fully qualified names

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-client-js#75]
the leading slash in a fully qualified name is optional but appears to break the library here if it's not specified.

for reference, see: https://github.com/apache/incubator-openwhisk/issues/2328

**Comment by jthomas** [comment]
The client library [currently supports](https://github.com/apache/incubator-openwhisk-client-js/blob/master/lib/names.js#L15-L30) the following resource identifiers.

```
- resource_name
- package/resource_name
- /namespace/resource_name
- /namespace/package/resource_name
```

If we want to support a missing forward-slash for fully qualified names, how does the API differentiate between `package/action` and `namespace/action`.

Does it only support that the missing forward slash for actions within packages?

**Comment by rabbah** [comment]
This is the backend change that was implemented for reference in the cli https://github.com/apache/incubator-openwhisk/pull/2424/files

Three parts: unambiguous hence can drop leading slash.
