### ISSUE TITLE
consider switching from request-promise to needle

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk-client-js#77]
request-promise depends on request, which is very slow to load: https://github.com/request/request/issues/2261

that issue aligns with my experience.  namely, that request-promise, due to request, can take anywhere from 120-250ms to `require` on mac and linux.

on windows 10, apparently due to windows defender, it can take 10 times as long! sometimes multiple seconds!

an alternative is needle: https://www.npmjs.com/package/needle

quick experiments show that needle indeed loads in about 1/4th the time. these numbers from macos 10.12.6, node 8.5.0: fairly stably needle loads in 30-32ms, and request-promise in 110-120ms.

in more realistic scenarios, i've seen request-promise routinely take close to 300ms on macos, and 1-3 seconds on windows 10. the fall creators update of windows 10 seems to have made this much worse.

the patch for this is straightforward, as needle mostly obeys the same schema as rp.

**Comment by jthomas** [comment]
:+1: on this. I had thought about moving away from `rp` before due to the size. Hadn't realised it had performance issues like this. 

Didn't know about `needle`, looks like a drop-in replacement. 

Provided all the tests pass this LGTM.
