### ISSUE TITLE
Add tests to improve coverage of error handling

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk-client-js#79]
Is it possible that the current test suite has no coverage of error handling? Because

1) earlier versions of PR  #78 didn't do proper error handling, but all of the integration and functional tests passed

2) with proper error handling, the PR still fails, because the codecov tool complains that the lines having to do with error handling (in my update) are not covered by tests!

**Comment by jthomas** [comment]
The client does have error handling tests in https://github.com/apache/incubator-openwhisk-client-js/blob/master/test/unit/client.test.js#L124-L142

Do the tests need to be more comprehensive to catch the new code?

**Comment by starpit** [comment]
I see. Yes, there may be a test gap for eg requesting a non existing action, package, etc. Or non-overwriting creates against an existing name, etc.
