### ISSUE TITLE
socket hangup issues due to slow connection open

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk-client-js#89]
we inherit needle's default connection-open timeout of 10 seconds. this seems to result in socket hangup errors. i'm not sure what the right solution is here, but wanted to raise awareness of it.

 - option 1: the user of this library has to retry
 - option 2: we update the openwhisk npm to retry, according to a policy established by the caller (e.g. maxRetries)
 - option 3: we increase the connection open timeout a bit, in tandem with either opt1 or opt2

this seems to happen often enough to be of note, when talking to ibm cloud functions

**Comment by starpit** [comment]
more info: this is actually an issue with the needle library, in the way it interprets or implements open timeout: https://github.com/tomas/needle/issues/229

**Comment by jthomas** [comment]
Interesting bug!

Reading the issue you reference, looks like they might resolve the bug in needle soon? If so, this should resolve this issue for us?

**Comment by starpit** [comment]
the owner of needle has a fix in the works. i've reviewed it, and it seems reasonable. i think it'll address our bug.

**Comment by epatters** [comment]
Thanks @starpit and others for your responsive handling of this issue. I see that the fix has just been incorporated into the runtime (apache/incubator-openwhisk-runtime-nodejs#18), so hopefully it will hit Bluemix soon.

Incidentally, I now understand why this bug manifested only recently: it coincided with the switch from promise-request to needle in this library (#78), which landed in v3.10.0 (#87).
