### ISSUE TITLE
Remove namespace list method.

### ISSUE THREAD

**Issue by jthomas** [apache/incubator-openwhisk-client-js#94]
API endpoint is being removed as per the discussion in:
https://github.com/apache/incubator-openwhisk/issues/3153

This should be replicated in the client library and published as a new major version.

**Comment by starpit** [comment]
can we sugar this in the npm? rather than having all clients sugar it?

**Comment by rabbah** [comment]
promise.all(actions.list(), packages.list(), ...)?

**Comment by starpit** [comment]
almost, each of the component promises needs to be .catch'd. i don't think we want the whole thing to fail fast if any one list call fails?

**Comment by rabbah** [comment]
To a first approximation, id think so - in case of error for one of the lists would you return an empty list in the catch?

**Comment by starpit** [comment]
this sounds good. do we need a side-band to report partial success? how does the backend API behave in this respect? if it fails fast, then we could just mimic that.

**Comment by jthomas** [comment]
Do people use this API endpoint regularly today? Is it used through the SDK in some of the project tools?

The client library has been kept as a thin wrapper over API until now. I was favouring removing this API, as the platform has, rather than shimming for this reason and as it didn't seem to have an obvious usage for most developers.

If we do use this a lot in other projects, that makes sense to add the shim proposed in the PR. Otherwise, I'd vote to remove it.

**Comment by starpit** [comment]
we did get a feature request for it in the shell. i was mostly hoping that we could break the backend, while breaking as few clients as possible. we could control this, by shipping an updated npm with the updated backend, etc.

i'd be ok marking the npm API as `@deprecated`

**Comment by jthomas** [comment]
@starpit If you have usage in shell, let's merge the PR above. It's simple enough.
